# Simplified Codemagic config - Build only, manual upload
# Use this if you want to upload to TestFlight manually

workflows:
  ios-build-only:
    name: iOS Build Only
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        PACKAGE_NAME: "com.saiko.app"
      node: 20
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Setup Capacitor
        script: |
          npm install -g @capacitor/cli
          # Remove iOS platform if it exists but is incomplete
          if [ -d "ios" ] && [ ! -f "ios/App/Podfile" ]; then
            echo "Removing incomplete iOS platform..."
            rm -rf ios
          fi
          # Add iOS platform if it doesn't exist
          if [ ! -d "ios" ]; then
            echo "Adding iOS platform..."
            npx cap add ios
            echo "iOS platform added"
          fi
          # Verify Podfile exists
          if [ ! -f "ios/App/Podfile" ]; then
            echo "ERROR: Podfile not found after adding iOS platform"
            echo "iOS directory contents:"
            ls -la ios/ || echo "ios directory doesn't exist"
            if [ -d "ios/App" ]; then
              echo "ios/App directory contents:"
              ls -la ios/App/ || echo "ios/App is empty"
            fi
            exit 1
          fi
          echo "Podfile found at ios/App/Podfile"
          echo "Syncing Capacitor..."
          npx cap sync ios
          echo "Capacitor sync completed"
      - name: Install CocoaPods dependencies
        script: |
          if [ ! -f "ios/App/Podfile" ]; then
            echo "ERROR: Podfile not found at ios/App/Podfile"
            exit 1
          fi
          echo "Installing CocoaPods dependencies..."
          cd ios/App && pod install && cd ../..
      - name: Create export options plist
        script: |
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
      - name: Build ipa
        script: |
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -allowProvisioningUpdates
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$CM_BUILD_DIR/build/ipa"
    artifacts:
      - build/ipa/*.ipa
